version: "3.9"
services:
  test_kreditplus:
    container_name: "test_kreditplus_v01"
    image: "test_kreditplus:0.0.1"
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports: 
      - 8080:8080
    networks:
      - test_golang_kreditplus

networks:
  test_golang_kreditplus: